# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('yue', models.FloatField()),
                ('liuru', models.FloatField()),
                ('shangzhang', models.IntegerField()),
                ('chiping', models.IntegerField()),
                ('xiadie', models.IntegerField()),
                ('createtime', models.DateTimeField()),
            ],
        ),
    ]
