# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_hgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgt',
            name='dapanzhangfu',
            field=models.FloatField(default=datetime.datetime(2016, 1, 18, 11, 16, 36, 941000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
